# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_mustbuylist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mustBuyList',
            new_name='Mustbuy',
        ),
    ]
