# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=150)),
                ('category_id', models.IntegerField(default=1)),
                ('brand_name', models.CharField(max_length=32)),
                ('img1', models.CharField(max_length=200)),
                ('child_cid1', models.IntegerField(default=1)),
                ('product_id1', models.IntegerField(default=1)),
                ('long_name1', models.CharField(max_length=128)),
                ('price1', models.FloatField(default=0)),
                ('market_price1', models.FloatField(default=0)),
                ('img2', models.CharField(max_length=200)),
                ('child_cid2', models.IntegerField(default=1)),
                ('product_id2', models.IntegerField(default=1)),
                ('long_name2', models.CharField(max_length=128)),
                ('price2', models.FloatField(default=0)),
                ('market_price2', models.FloatField(default=0)),
                ('img3', models.CharField(max_length=200)),
                ('child_cid3', models.IntegerField(default=1)),
                ('product_id3', models.IntegerField(default=1)),
                ('long_name3', models.CharField(max_length=128)),
                ('price3', models.FloatField(default=0)),
                ('market_price3', models.FloatField(default=0)),
            ],
        ),
    ]
