# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_mainshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='brand_name',
            new_name='brandname',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='category_id',
            new_name='categoryid',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='child_cid1',
            new_name='childcid1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='child_cid2',
            new_name='childcid2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='child_cid3',
            new_name='childcid3',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='long_name1',
            new_name='longname1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='long_name2',
            new_name='longname2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='long_name3',
            new_name='longname3',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='market_price1',
            new_name='marketprice1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='market_price3',
            new_name='marketprice2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='market_price2',
            new_name='marketprice3',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='product_id1',
            new_name='productid1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='product_id2',
            new_name='productid2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='product_id3',
            new_name='productid3',
        ),
    ]
